name: Clean up on cron job

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
env:
  SITE_DIR: ${{ github.ref }}
  #SITE_DIR: subsite
on:
  workflow_dispatch:
  # We have another workflow for pushing directly to dev
  #schedule:
    # * is a special character in YAML so you have to quote this string
    # 0300 every sunday
  #  - cron:  '0 3 * * SUN'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-html:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
         
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
          
    - name: Create container in Azure blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az login --service-principal -u 172103f9-7886-4f00-a49e-621461d234e1 -p ${{ secrets.DOCSBOT_SECRET }} --tenant 07dc27cd-da6f-4de6-b83d-c4eed0a10602
            az storage container create --name pr${{ steps.findandreplace.outputs.value }} --public-access container --account-name quixdocsdev --auth-mode key

            az login --service-principal -u 172103f9-7886-4f00-a49e-621461d234e1 -p ${{ secrets.DOCSBOT_SECRET }} --tenant 07dc27cd-da6f-4de6-b83d-c4eed0a10602
            az storage container list --account-name quixdocsdev --auth-mode key

            az login --service-principal -u 172103f9-7886-4f00-a49e-621461d234e1 -p ${{ secrets.DOCSBOT_SECRET }} --tenant 07dc27cd-da6f-4de6-b83d-c4eed0a10602
            date=`date -d "7 days ago" '+%Y-%m-%dT%H:%MZ'`
            az storage container delete --account-name quixdocsdev --auth-mode key --name pr${{ steps.findandreplace.outputs.value }} --if-unmodified-since $date
            
  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
      
    - name: Send Slack notification
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "Clean up",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Old deployments have been deleted. Anything over 7 days old has gone to the scrap heap!"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
